//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckInventory.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TruckInventory.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TRUCKS {
            get {
                return ResourceManager.GetString("TRUCKS", resourceCulture);
            }
        }
        
        internal static string ADD_TRUCK {
            get {
                return ResourceManager.GetString("ADD_TRUCK", resourceCulture);
            }
        }
        
        internal static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        internal static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        internal static string AVAILABLE {
            get {
                return ResourceManager.GetString("AVAILABLE", resourceCulture);
            }
        }
        
        internal static string IS_AVAILABLE {
            get {
                return ResourceManager.GetString("IS_AVAILABLE", resourceCulture);
            }
        }
        
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        internal static string MAKE {
            get {
                return ResourceManager.GetString("MAKE", resourceCulture);
            }
        }
        
        internal static string EDIT_OR_DELETE {
            get {
                return ResourceManager.GetString("EDIT_OR_DELETE", resourceCulture);
            }
        }
        
        internal static string PURCHASE_DATE {
            get {
                return ResourceManager.GetString("PURCHASE_DATE", resourceCulture);
            }
        }
        
        internal static string TRUCK_ID {
            get {
                return ResourceManager.GetString("TRUCK_ID", resourceCulture);
            }
        }
        
        internal static string MAX_6_CHARACTERS {
            get {
                return ResourceManager.GetString("MAX_6_CHARACTERS", resourceCulture);
            }
        }
        
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        internal static string TRUCK_DETAIL {
            get {
                return ResourceManager.GetString("TRUCK_DETAIL", resourceCulture);
            }
        }
        
        internal static string CHANGES_SAVED_MESSAGE {
            get {
                return ResourceManager.GetString("CHANGES_SAVED_MESSAGE", resourceCulture);
            }
        }
        
        internal static string EDIT_OR_DELETE_MESSAGE {
            get {
                return ResourceManager.GetString("EDIT_OR_DELETE_MESSAGE", resourceCulture);
            }
        }
        
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        internal static string PHOTO_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("PHOTO_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        internal static string DELETE_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        internal static string PHOTO {
            get {
                return ResourceManager.GetString("PHOTO", resourceCulture);
            }
        }
        
        internal static string ADD_PHOTO {
            get {
                return ResourceManager.GetString("ADD_PHOTO", resourceCulture);
            }
        }
        
        internal static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        internal static string LIBRARY {
            get {
                return ResourceManager.GetString("LIBRARY", resourceCulture);
            }
        }
        
        internal static string CAMERA_OR_LIBRARY_CONFIRMATION {
            get {
                return ResourceManager.GetString("CAMERA_OR_LIBRARY_CONFIRMATION", resourceCulture);
            }
        }
        
        internal static string MANUFACTURER_REQUIRED_MESSAGE {
            get {
                return ResourceManager.GetString("MANUFACTURER_REQUIRED_MESSAGE", resourceCulture);
            }
        }
        
        internal static string ID_REQUIRED_MESSAGE {
            get {
                return ResourceManager.GetString("ID_REQUIRED_MESSAGE", resourceCulture);
            }
        }
        
        internal static string LICENSE_INVALID_FORMAT_MESSAGE {
            get {
                return ResourceManager.GetString("LICENSE_INVALID_FORMAT_MESSAGE", resourceCulture);
            }
        }
        
        internal static string ALERT {
            get {
                return ResourceManager.GetString("ALERT", resourceCulture);
            }
        }
        
        internal static string UNSAVED_CHANGES_MESSAGE {
            get {
                return ResourceManager.GetString("UNSAVED_CHANGES_MESSAGE", resourceCulture);
            }
        }
    }
}
